### ISSUE TITLE
./scripts/server.sh " Couldn't get a file descriptor referring to the console"

### ISSUE THREAD

**Issue by nguyenthong** [angularjs-foundation/video-exercises#10]
hi

When I run the the server.sh it got a problem with the message is "Couldn't get a file descriptor referring to the console" and I stuck at that point

**Comment by simpulton** [comment]
Hello --
Could you give me some more details? What operating system are you using? Etc. Thanks!

**Comment by stevenjahlstrom** [comment]
On windows 7, using PowerShell

PS C:\sandbox\Angular\oreilly\video-exercises> scripts\server.cmd

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1023:19)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by simpulton** [comment]
Hello @mortsahl -- is something else already running on that port when you run the script?
